server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: Mecipe
    version: 0.0.1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mecipe_server?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: password
    hikari:
      pool-name: cn-acl-db-pool
      minimum-idle: 5 # 最小空闲连接数量
      idle-timeout: 180000 # 空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 30 # 连接池最大连接数，默认是10
      auto-commit: true  # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 # 数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1 from dual

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: mecipe-token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # 是否允许同一账号并发登录
  is-concurrent: true
  # 关闭Cookie模式
  isReadCookie: true
  # 在多人登录同一账号时，是否共用一个token
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.mecipe.server.controller